services:
  - type: web
    name: simurghpdf-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    packages:                 # Debian packages Render pre-installs
      - ghostscript
      - poppler-utils         # already for pdf2docx
      - tesseract-ocr         # OCR engine
      - libtesseract-dev      # header files (needed on some images)
