services:
  - type: web
    name: perkpdf-api
    runtime: python
    pythonVersion: "3.11.7"
    region: frankfurt
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PYTHONPATH
        value: /opt/render/project/src
